name: Release (semantic-release)

on:
  push:
    branches:
      - main
      - next
  workflow_dispatch: {}

permissions:
  contents: write    # 릴리스/태그 작성
  issues: write      # (옵션) 릴리스 결과 코멘트 등
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 커밋/태그 이력 필요
          fetch-tags: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: npm ci

      # (옵션) 테스트/빌드
      # - name: Test
      #   run: npm test
      # - name: Build
      #   run: npm run build

      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release

